blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & Discussions
    url: https://github.com/yasinatesim/vela-commerce/discussions
    about: Ask questions and discuss ideas with the community.
